(function (global) {
  "use strict";
  const G = global.Guiden, C = G.core;
  const jsonOnly = "Return JSON only. Do not use Markdown or code fences.";
  function base(snapshot) { return "Range: " + snapshot.targetLabel + "\nRows: " + snapshot.rows + "\nColumns: " + snapshot.cols + "\nValues (tab-delimited):\n" + snapshot.text + "\nFormulas (tab-delimited; never overwrite these):\n" + snapshot.formulas.map(r => r.join("\t")).join("\n"); }
  function request(system, snapshot, instruction, extra) { return C.groundedMessages(system, base(snapshot) + String(extra || ""), instruction); }
  function parseAnswer(content) { const d = C.extractJson(content); if (typeof d.answer !== "string") throw new Error("Guiden returned an invalid analysis."); return { answer: d.answer, table: Array.isArray(d.table) ? d.table : [], sources: C.safeSources(d.sources) }; }
  function destinationRight(snapshot) { const start = { startRow: snapshot.start.startRow, startCol: snapshot.start.endCol + 1 }; return { start, address: C.rangeAddress(start, snapshot.rows, 1) }; }
  function isEmpty(value) { return C.normalizeMatrix(value).every(r => r.every(v => String(v == null ? "" : v).trim() === "")); }
  async function requireEmpty(address) { const read = await G.host.readRange(address); if (!read || !read.ok) throw new Error("The destination could not be checked safely."); if (!isEmpty(read.values) || !isEmpty(read.formulas)) throw new Error("The displayed destination is no longer empty. Generate again or choose another destination."); }
  function register(action) { G.registerAction(Object.assign({ editor: "cell", supportedTargets: ["selection"] }, action)); }

  register({ id: "cells.ask", label: "Analyse selection", description: "Find trends, outliers, risks, or answers", mutates: false, defaultInstruction: "Analyse this selection and explain the useful findings.", placeholder: "What would you like to learn from these cells?",
    buildRequest(snapshot, instruction) { return request("You are Guiden inside Euro-Office Cells. Analyse only; never propose cell mutations. Return JSON: {\"answer\":\"...\",\"table\":[],\"sources\":[]}. " + jsonOnly, snapshot, instruction); }, parseResponse: parseAnswer,
    buildPreview(result) { return { kind: "analysis", answer: result.answer, table: result.table, sources: result.sources }; }, revalidateTarget: async () => ({ ok: true }), apply: async () => { throw new Error("Analysis is read-only."); } });

  register({ id: "cells.edit", label: "Clean/edit values", description: "Change only the cells that need it", mutates: true, defaultInstruction: "Clean inconsistent text and labels while preserving meaning and data types.", placeholder: "Describe the values to clean or edit.",
    buildRequest(snapshot, instruction) { return request("Edit selected spreadsheet values using sparse zero-based coordinates relative to the selected range. Preserve formulas, numbers, booleans, and untouched cells. Return {\"narrative\":\"...\",\"updates\":[{\"row\":0,\"column\":0,\"before\":\"exact original\",\"after\":\"new value\"}]}. " + jsonOnly, snapshot, instruction); },
    parseResponse(content, snapshot) { const d = C.extractJson(content); return { narrative: String(d.narrative || ""), updates: C.validateUpdates(d.updates, snapshot) }; },
    buildPreview(result, snapshot) { return { kind: "cell-updates", narrative: result.narrative, updates: result.updates, snapshot }; }, revalidateTarget: snapshot => G.host.revalidate(snapshot), apply: (result, snapshot) => G.host.applyCellUpdates(result.updates, snapshot) });

  register({ id: "cells.formula", label: "Create formula", description: "Build one formula for the selected cell", mutates: true, defaultInstruction: "Create the requested formula for the selected cell.", placeholder: "What should the formula calculate?",
    buildRequest(snapshot, instruction) { return request("Create exactly one Excel/Euro-Office compatible formula beginning with =. Return {\"formula\":\"=...\",\"explanation\":\"...\"}. " + jsonOnly, snapshot, instruction, "\nDestination: " + C.rangeAddress(snapshot.start, 1, 1)); },
    parseResponse(content) { const d = C.extractJson(content); if (typeof d.formula !== "string" || !/^=/.test(d.formula.trim())) throw new Error("Guiden did not return a valid formula."); return { formula: d.formula.trim(), explanation: String(d.explanation || "") }; },
    buildPreview(result, snapshot) { return { kind: "formula", formula: result.formula, explanation: result.explanation, address: C.rangeAddress(snapshot.start, 1, 1), before: snapshot.values[0] && snapshot.values[0][0] }; }, revalidateTarget: snapshot => G.host.revalidate(snapshot), apply(result, snapshot) { return G.host.applyFormula(C.rangeAddress(snapshot.start, 1, 1), result.formula); } });

  function columnAction(id, label, description, classify) {
    register({ id, label, description, mutates: true, defaultInstruction: classify ? "Classify every data row into a concise category." : "Add the requested calculated column.", placeholder: classify ? "How should the rows be classified?" : "What should the new column calculate?",
      buildRequest(snapshot, instruction) { const count = Math.max(0, snapshot.rows - 1), system = classify ? "Return one category per data row. Return {\"header\":\"Category\",\"values\":[" + Array(count).fill("\"value\"").join(",") + "],\"narrative\":\"...\"}. values must contain exactly " + count + " items. " + jsonOnly : "Return a calculated-column header and one Excel-compatible formula for each data row. Return {\"header\":\"...\",\"formulas\":[" + Array(count).fill("\"=...\"").join(",") + "],\"narrative\":\"...\"}. formulas must contain exactly " + count + " items. " + jsonOnly; return request(system, snapshot, instruction); },
      parseResponse(content, snapshot) { const d = C.extractJson(content), values = classify ? d.values : d.formulas; if (typeof d.header !== "string" || !d.header.trim() || !Array.isArray(values) || values.length !== Math.max(0, snapshot.rows - 1)) throw new Error("Guiden did not return one result for every data row."); if (!classify && values.some(v => typeof v !== "string" || !/^=/.test(v.trim()))) throw new Error("Guiden returned an invalid calculated-column formula."); return { header: d.header.trim(), values, narrative: String(d.narrative || "") }; },
      buildPreview(result, snapshot) { const dest = destinationRight(snapshot); return { kind: "new-column", narrative: result.narrative, header: result.header, values: result.values, address: dest.address, formula: !classify }; },
      revalidateTarget: snapshot => G.host.revalidate(snapshot), async apply(result, snapshot) { const dest = destinationRight(snapshot); await requireEmpty(dest.address); const values = [result.header].concat(result.values), fake = { start: dest.start, address: dest.address }; const updates = values.map((value, row) => ({ row, column: 0, after: value })); if (classify) return G.host.applyCellUpdates(updates, fake); let changed = 0; await G.host.applyCellUpdates([{ row: 0, column: 0, after: result.header }], fake); changed += 1; for (let row = 1; row < values.length; row += 1) { await G.host.applyFormula(C.rangeAddress({ startRow: dest.start.startRow + row, startCol: dest.start.startCol }, 1, 1), values[row]); changed += 1; } return { ok: true, changed, target: dest.address, warnings: [] }; }
    });
  }
  columnAction("cells.add_column", "Add calculated column", "Create formulas in a new column", false);
  columnAction("cells.classify", "Classify rows", "Add one category for each data row", true);

  register({ id: "cells.format", label: "Format cells", description: "Apply colours, alignment, and number formats", mutates: true, defaultInstruction: "Format the selected cells as requested without changing values.", placeholder: "For example: colour values below 83 red.",
    buildRequest(snapshot, instruction) { return request("Format existing selected cells without changing any value or formula. Return {\"narrative\":\"...\",\"styles\":[{\"target\":{\"type\":\"condition\",\"column\":0,\"operator\":\"lt\",\"value\":83},\"fill\":\"#FECACA\",\"fontColor\":\"#991B1B\"}]}. Targets: cell(row,column), row(start,end), column(start,end), condition(column,operator,value). Operators: lt,lte,gt,gte,eq,neq,contains. Styles: fill,fontColor,bold,italic,align,numberFormat. Use zero-based coordinates. Do not add header formatting or borders unless explicitly requested. " + jsonOnly, snapshot, instruction); },
    parseResponse(content, snapshot) { const d = C.extractJson(content), styles = C.validateStyles(d.styles, snapshot), cells = C.expandStyleRules(styles, snapshot); if (!cells.length) throw new Error("No selected cells match the requested formatting."); return { narrative: String(d.narrative || ""), styles, cells }; },
    buildPreview(result, snapshot) { return { kind: "formatting", narrative: result.narrative, cells: result.cells, snapshot }; }, revalidateTarget: snapshot => G.host.revalidate(snapshot), apply: (result, snapshot) => G.host.applyStyles(result.cells, snapshot) });

  register({ id: "cells.table", label: "Create table", description: "Generate a new table from the starting cell", mutates: true, defaultInstruction: "Create a useful structured table.", placeholder: "Describe the table and data you need.",
    buildRequest(snapshot, instruction, options) { return request("Create a rectangular spreadsheet table. Return {\"narrative\":\"...\",\"table\":[[\"Header\"],[\"Value\"]]}. Preserve number and boolean types. " + jsonOnly, snapshot, instruction, "\nTheme: " + options.tableTheme); },
    parseResponse(content) { const d = C.extractJson(content); if (!Array.isArray(d.table) || !d.table.length || !Array.isArray(d.table[0]) || !d.table[0].length) throw new Error("Guiden did not return a table."); const width = d.table[0].length; if (!d.table.every(r => Array.isArray(r) && r.length === width)) throw new Error("Guiden returned a non-rectangular table."); if (d.table.length > 500 || width > 100) throw new Error("The generated table is too large to apply safely."); return { narrative: String(d.narrative || ""), table: d.table }; },
    buildPreview(result, snapshot) { const address = C.rangeAddress(snapshot.start, result.table.length, result.table[0].length); return { kind: "table", narrative: result.narrative, table: result.table, address, warning: "Guiden will confirm that the entire destination is empty before applying." }; },
    revalidateTarget: snapshot => G.host.revalidate(snapshot), async apply(result, snapshot) { const address = C.rangeAddress(snapshot.start, result.table.length, result.table[0].length); await requireEmpty(address); const tableSnapshot = { rows: result.table.length, cols: result.table[0].length, values: result.table }; const rules = C.validateStyles([{ target: { type: "row", start: 0, end: 0 }, fill: "#2954A2", fontColor: "#FFFFFF", bold: true }], tableSnapshot); const styles = C.expandStyleRules(rules, tableSnapshot); return G.host.applyTable(result.table, address, styles); } });
})(window);
