(function (global) {
  "use strict";
  const G = global.Guiden, C = G.core;
  const jsonOnly = "Return JSON only. Do not use Markdown or code fences.";
  function source(snapshot, options) { return "Target: " + snapshot.targetLabel + "\nTone: " + options.tone + "\nLength: " + options.length + "\n\nIndexed slide content:\n" + snapshot.text; }
  function request(system, snapshot, instruction, options) { return C.groundedMessages(system, source(snapshot, options), instruction); }
  function answer(content) { const d = C.extractJson(content); if (typeof d.answer !== "string") throw new Error("Guiden returned an invalid slide answer."); return { answer: d.answer, sources: C.safeSources(d.sources) }; }
  function selectedReplacement(content) { const d = C.extractJson(content); if (typeof d.replacementText !== "string") throw new Error("Guiden did not return replacement slide text."); return { replacementText: d.replacementText }; }
  function shapeUpdates(content, snapshot) { const d = C.extractJson(content); return { narrative: String(d.narrative || ""), updates: C.validateShapeUpdates(d.updates, snapshot) }; }
  function register(action) { G.registerAction(Object.assign({ editor: "slide", supportedTargets: ["selected_text", "current_slide"] }, action)); }
  register({ id: "slides.ask", label: "Ask", description: "Ask about the current slide", mutates: false, defaultInstruction: "Answer my question about this slide.", placeholder: "What would you like to know about this slide?", buildRequest(snapshot, instruction, options) { return request("You are Guiden inside Euro-Office Slides. Answer without changing the presentation. Return {\"answer\":\"...\",\"sources\":[]}. " + jsonOnly, snapshot, instruction, options); }, parseResponse: answer, buildPreview(result) { return { kind: "answer", answer: result.answer, sources: result.sources }; }, revalidateTarget: async () => ({ ok: true }), apply: async () => { throw new Error("This action is read-only."); } });
  function edit(id, label, description, defaultInstruction, selectedOnly) {
    register({ id, label, description, mutates: true, supportedTargets: selectedOnly ? ["selected_text"] : ["selected_text", "current_slide"], defaultInstruction, placeholder: "Add any preferences, or leave blank.",
      buildRequest(snapshot, instruction, options) { const selected = snapshot.target === "selected_text", system = selected ? "Improve only the selected slide text. Return {\"replacementText\":\"...\"}. " + jsonOnly : "Update only identified text areas. Preserve unmentioned shapes and all non-text objects. Return {\"narrative\":\"...\",\"updates\":[{\"shapeIndex\":0,\"before\":\"exact original\",\"after\":\"new text\"}]}. shapeIndex must match an indexed area. " + jsonOnly; return request(system, snapshot, instruction || defaultInstruction, options); },
      parseResponse(content, snapshot) { if (selectedOnly && snapshot.target !== "selected_text") throw new Error("Select text on the slide before using this action."); return snapshot.target === "selected_text" ? selectedReplacement(content) : shapeUpdates(content, snapshot); },
      buildPreview(result, snapshot) { return snapshot.target === "selected_text" ? { kind: "text-diff", before: snapshot.selectedText, after: result.replacementText } : { kind: "shape-updates", narrative: result.narrative, updates: result.updates }; },
      revalidateTarget: snapshot => G.host.revalidate(snapshot), apply(result, snapshot) { return snapshot.target === "selected_text" ? G.host.applySelectedSlideText(result.replacementText, snapshot) : G.host.applyShapeUpdates(result.updates, snapshot); }
    });
  }
  edit("slides.improve", "Improve selected text", "Polish only selected slide text", "Improve clarity and impact while keeping it slide-ready.", true);
  edit("slides.shorten", "Shorten current slide", "Reduce text while preserving key points", "Shorten the slide substantially and keep the important message.", false);
  edit("slides.rewrite", "Rewrite current slide", "Improve identified text areas safely", "Rewrite the current slide for clarity and impact.", false);
  register({ id: "slides.new", label: "Create new slide", description: "Add one title-and-bullets slide", mutates: true, defaultInstruction: "Create one useful new slide.", placeholder: "Describe the slide you want to add.",
    buildRequest(snapshot, instruction, options) { return request("Create one concise slide. Return {\"title\":\"...\",\"bullets\":[\"...\"],\"themeRole\":\"content\"}. Use at most 6 bullets. " + jsonOnly, snapshot, instruction, options); },
    parseResponse(content) { const d = C.extractJson(content); if (typeof d.title !== "string" || !d.title.trim() || !Array.isArray(d.bullets) || !d.bullets.length || d.bullets.length > 6) throw new Error("Guiden did not return a valid slide."); return { title: d.title.trim(), bullets: d.bullets.map(String), themeRole: String(d.themeRole || "content") }; },
    buildPreview(result) { return { kind: "new-slide", title: result.title, bullets: result.bullets }; }, revalidateTarget: snapshot => G.host.revalidate(snapshot), apply: result => G.host.createSlide(result) });
  register({ id: "slides.outline", label: "Create slide outline", description: "Preview a presentation structure", mutates: false, defaultInstruction: "Create a concise slide outline from this content.", placeholder: "What should the outline cover?",
    buildRequest(snapshot, instruction, options) { return request("Create a presentation outline. Return {\"answer\":\"short overview\",\"slides\":[{\"title\":\"...\",\"bullets\":[\"...\"]}],\"sources\":[]}. Return no more than " + options.slideCount + " slides. " + jsonOnly, snapshot, instruction, options); },
    parseResponse(content) { const d = C.extractJson(content); if (!Array.isArray(d.slides)) throw new Error("Guiden did not return a slide outline."); return { answer: String(d.answer || "Slide outline"), slides: d.slides, sources: C.safeSources(d.sources) }; }, buildPreview(result) { return { kind: "outline", answer: result.answer, slides: result.slides, sources: result.sources }; }, revalidateTarget: async () => ({ ok: true }), apply: async () => { throw new Error("The outline is read-only. Choose Create new slide to add a slide."); } });
  register({ id: "slides.notes", label: "Generate speaker notes", description: "Add notes without changing slide content", mutates: true, defaultInstruction: "Create useful speaker notes for this slide.", placeholder: "What should the speaker notes emphasise?",
    buildRequest(snapshot, instruction, options) { return request("Create speaker notes for the current slide. Return {\"notes\":\"plain text notes\"}. " + jsonOnly, snapshot, instruction, options); }, parseResponse(content) { const d = C.extractJson(content); if (typeof d.notes !== "string" || !d.notes.trim()) throw new Error("Guiden did not return speaker notes."); return { notes: d.notes.trim() }; }, buildPreview(result) { return { kind: "notes", notes: result.notes }; }, revalidateTarget: snapshot => G.host.revalidate(snapshot), apply: (result, snapshot) => G.host.addNotes(result.notes, snapshot) });
})(window);
